# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hc43cgZf2QCwqsXhMfa4HA2Rumazx9yd
"""

import re
import string

# Reading text file
file=open("/content/HP1.txt", "r")
content = file.read()
print(content)
file.close()

#Reading a first 10 sentences
sent = re.split(r'[.!?]', content)[:10]
para_content = ' '.join(s.strip() for s in sent if s.strip())
print(para_content)

# Split the text by whitespace
split = content.split()
print(split)

#remove punctuation
translator = str.maketrans('', '', string.punctuation)
content = content.translate(translator).lower()
clean = [word for word in content.split() if word]
clean = [word.replace("'s",'') for word in clean]

print(clean)

#Extract unique words from the text and collect them in an array
unique = []
seen=set()
for word in clean:
    if word not in seen:
        unique.append(word)
        seen.add(word)

print(unique)

#Map each word to a unique index

index = {word: i for i, word in enumerate(unique)}
print(index)

# Create dataset with words as inputs and 2-word context as labels
def create_dataset(clean, index, window=2):
    data = []
    for i, target_word in enumerate(clean):
        context_indices = list(range(max(0, i - window), i)) + list(range(i + 1, min(len(clean), i + window + 1)))
        for j in context_indices:
            data.append((index[target_word], index[clean[j]]))
    return data

dataset = create_dataset(clean, index)
print("Dataset size:", len(dataset))
dataset[:10]

